### ISSUE TITLE
Trouver un logo (E26)

### ISSUE THREAD

**Issue by jvrbn** [gti525/e18-banque#15]

**Comment by pgodbout** [comment]
En tant que développeur, je dois imaginer des logos pouvant être utilisés comme image de marque.

**Comment by fodil1** [comment]
Un logo dans le même style que celui la.

https://www.google.ca/imgres?imgurl=http%3A%2F%2Fwww.uppotential.com%2Fen%2Fassets%2Fuploads%2Fimages%2F%25E4%25B8%258D%25E9%2580%2580%25E6%25AC%25BE%25E6%2594%25BF%25E7%25AD%2596.png&imgrefurl=http%3A%2F%2Fwww.uppotential.com%2Fen%2Fnon-refund-policy%2F&docid=LuQ70e9eFxLseM&tbnid=YZPWCoLy-j3OVM%3A&vet=10ahUKEwiNrubls4HbAhWFmOAKHSwtBe4QMwiYAShXMFc..i&w=2133&h=2133&bih=1292&biw=2559&q=no%20refund%20&ved=0ahUKEwiNrubls4HbAhWFmOAKHSwtBe4QMwiYAShXMFc&iact=mrc&uact=8
